apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <html>
    <head>
        <title>Hello from Nginx</title>
    </head>
    <body>
        <h1>Hello, Kubernetes!</h1>
        <p>This is a sample application running in a Kubernetes pod.</p>
    </body>
    </html>
