# Use the official Python image as a base
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the application code to the container
COPY hello.py .

# Define the command to run the application
CMD ["python", "hello.py"]