apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-deleter-binding
  namespace: default
subjects:
- kind: User
  name: userdelete@yourdomain.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-deleter
  apiGroup: rbac.authorization.k8s.io
